# NDArray basics

NDArray functions let users perform different operations with NDArray arrays like setting, copying or slicing them.
In this section, we are going to see how to create and manipulate a NDArray array in a simple way.


In [39]:
import blosc2
import numpy as np

## Creating an array
First, we create an array, with zeros being used as the default value for uninitialized portions of the array.


In [40]:
array = blosc2.zeros((10000, 10000), dtype=np.int32)
array.info

{
    'blocksize': 131072,
    'clevel': 1,
    'codec': <Codec.ZSTD: 5>,
    'codec_meta': 0,
    'filters': [
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.SHUFFLE: 1>
    ],
    'filters_meta': [0, 0, 0, 0, 0, 0],
    'nthreads': 2,
    'splitmode': <SplitMode.ALWAYS_SPLIT: 1>,
    'typesize': 4,
    'use_dict': 0
}

{'nthreads': 2}

type    : NDArray
shape   : (10000, 10000)
chunks  : (512, 1024)
blocks  : (128, 256)
dtype   : int32
cratio  : 65536.00
cparams : 
dparams :

Note that all the compression and decompression parameters, as well as the chunks and blocks shapes are set to the default.

## Reading and writing data
We can access and edit NDArray arrays using NumPy.

In [41]:
array[0, :] = np.arange(10000, dtype=array.dtype)
array[:, 0] = np.arange(10000, dtype=array.dtype)

In [42]:
array[0, 0]

array(0, dtype=int32)

In [43]:
array[0, :]

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int32)

In [44]:
array[:, 0]

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int32)

In [45]:
array[...]

array([[   0,    1,    2, ..., 9997, 9998, 9999],
       [   1,    0,    0, ...,    0,    0,    0],
       [   2,    0,    0, ...,    0,    0,    0],
       ...,
       [9997,    0,    0, ...,    0,    0,    0],
       [9998,    0,    0, ...,    0,    0,    0],
       [9999,    0,    0, ...,    0,    0,    0]], dtype=int32)

## Persistent data
As in the SChunk, when we create a NDArray array, we can specify where it will be stored. Indeed, we can specify all the compression/decompression parameters that we can specify in a SChunk.
So as in the SChunk, to store an array on-disk we only have to specify a `urlpath` where to store the new array.


In [47]:
array = blosc2.full((1000, 1000), fill_value=b"pepe", chunks=(100, 100), blocks=(50, 50),
             urlpath="ndarray_tutorial.b2nd", mode="w")
array.info

{
    'blocksize': 10000,
    'clevel': 1,
    'codec': <Codec.ZSTD: 5>,
    'codec_meta': 0,
    'filters': [
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.SHUFFLE: 1>
    ],
    'filters_meta': [0, 0, 0, 0, 0, 0],
    'nthreads': 2,
    'splitmode': <SplitMode.ALWAYS_SPLIT: 1>,
    'typesize': 4,
    'use_dict': 0
}

{'nthreads': 2}

type    : NDArray
shape   : (1000, 1000)
chunks  : (100, 100)
blocks  : (50, 50)
dtype   : |S4
cratio  : 1111.11
cparams : 
dparams :

This time we even set the chunks and blocks shapes.

## Updating and inserting

First, let's update the first chunk:

In [48]:
array2 = blosc2.open("ndarray_tutorial.b2nd")

array2.info

{
    'blocksize': 10000,
    'clevel': 1,
    'codec': <Codec.ZSTD: 5>,
    'codec_meta': 0,
    'filters': [
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.SHUFFLE: 1>
    ],
    'filters_meta': [0, 0, 0, 0, 0, 0],
    'nthreads': 2,
    'splitmode': <SplitMode.ALWAYS_SPLIT: 1>,
    'typesize': 4,
    'use_dict': 0
}

{'nthreads': 2}

type    : NDArray
shape   : (1000, 1000)
chunks  : (100, 100)
blocks  : (50, 50)
dtype   : |S4
cratio  : 1111.11
cparams : 
dparams :

## Compression params
Here we can see how when we make a copy of a NDArray array we can change its compression parameters in an easy way.

In [49]:
b = np.arange(1000000).tobytes()

array1 = blosc2.frombuffer(b, shape=(1000, 1000), dtype=np.int64, chunks=(500, 10), blocks=(50, 10))

array1.info

{
    'blocksize': 4000,
    'clevel': 1,
    'codec': <Codec.ZSTD: 5>,
    'codec_meta': 0,
    'filters': [
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.SHUFFLE: 1>
    ],
    'filters_meta': [0, 0, 0, 0, 0, 0],
    'nthreads': 2,
    'splitmode': <SplitMode.ALWAYS_SPLIT: 1>,
    'typesize': 8,
    'use_dict': 0
}

{'nthreads': 2}

type    : NDArray
shape   : (1000, 1000)
chunks  : (500, 10)
blocks  : (50, 10)
dtype   : int64
cratio  : 7.45
cparams : 
dparams :

In [50]:
cparams = {
    "codec": blosc2.Codec.ZSTD,
    "clevel": 9,
    "filters": [blosc2.Filter.BITSHUFFLE],
    "filters_meta": [0]
}

array2 = array1.copy(chunks=(500, 10), blocks=(50, 10), cparams=cparams)

array2.info

{
    'blocksize': 4000,
    'clevel': 9,
    'codec': <Codec.ZSTD: 5>,
    'codec_meta': 0,
    'filters': [
        <Filter.BITSHUFFLE: 2>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>,
        <Filter.NOFILTER: 0>
    ],
    'filters_meta': [0, 0, 0, 0, 0, 0],
    'nthreads': 2,
    'splitmode': <SplitMode.ALWAYS_SPLIT: 1>,
    'typesize': 8,
    'use_dict': 0
}

{'nthreads': 2}

type    : NDArray
shape   : (1000, 1000)
chunks  : (500, 10)
blocks  : (50, 10)
dtype   : int64
cratio  : 13.94
cparams : 
dparams :

## Metalayers and variable length metalayers

We have seen that you can pass to the NDArray constructor any compression or decompression parameters that you may pass to a SChunk. Indeed, you can also pass the metalayer dict. Metalayers are small metadata for informing about the properties of data that is stored on a container. As explained in [the SChunk basics](00.schunk-basics.html), there are two kinds. The first one (`meta`), cannot be deleted, must be added at construction time and can only be updated with values that have the same bytes size as the old value. They are easy to access and edit by users:

In [51]:
meta = {
    "dtype": "i8",
    "coords": [5.14, 23.]
}
array = blosc2.zeros((1000, 1000), dtype=np.int16, chunks=(100, 100), blocks=(50, 50), meta=meta)


You can work with them like if you were working with a dictionary. To access this dictionary you will use the SChunk attribute that an NDArray has.

In [52]:
array.schunk.meta

In [53]:
array.schunk.meta.keys()

['b2nd', 'dtype', 'coords']

As you can see, Blosc2 internally uses these metalayers to store shapes, ndim, dtype, etc, and retrieve this data when needed in the `b2nd` metalayer.

In [54]:
array.schunk.meta["b2nd"]

[0, 2, [1000, 1000], [100, 100], [50, 50], 0, '<i2']

In [55]:
array.schunk.meta["coords"]

[5.14, 23.0]

To add a metalayer after the creation or a variable length metalayer, you can use the `vlmeta` accessor from the SChunk. As well as the `meta`, it works similarly to a dictionary.

In [56]:
print(array.schunk.vlmeta.getall())
array.schunk.vlmeta["info1"] = "This is an example"
array.schunk.vlmeta["info2"] = "of user meta handling"
array.schunk.vlmeta.getall()

{}


{b'info1': 'This is an example', b'info2': 'of user meta handling'}

You can update them with a value larger than the original one:

In [57]:
array.schunk.vlmeta["info1"] = "This is a larger example"
array.schunk.vlmeta.getall()

{b'info1': 'This is a larger example', b'info2': 'of user meta handling'}

That's all for now.  There are more examples in the [examples directory of the git repository](https://github.com/Blosc/python-blosc2/tree/main/examples/) for you to explore.  Enjoy!